#!/bin/bash

# By: Aidan Biggs
# AKA AT Vloggers
# 
# Please do not claim this as your own.
# 
# If you remove this it means you break the Code of Use found here: 
# https://at-vloggers.weebly.com/code-of-use.html

cd Desktop
echo AUTO SCRIPT SAVER
echo SCRIPT NAME: $1
chmod +x $1
sudo cp $1 /usr/bin/
echo DONE
